---
- name:             'Create CTX'
  hosts:            'all'
  tasks:
# Create new container with minimal options
  - proxmox:
      vmid:         300
      node:         pve01
      api_user:     root@pam
      api_password: thc401
      api_host:     pve01
      password:     thc401
      hostname:     ctx01.local
      ostemplate:   'local:vztmpl/ubuntu-19.10-standard_19.10-1_amd64.tar.gz'
